export const CREATE_TUTORIAL = "CREATE_TUTORIAL";
export const RETRIEVE_TUTORIALS = "RETRIEVE_TUTORIALS";
export const UPDATE_TUTORIAL = "UPDATE_TUTORIAL";
export const DELETE_TUTORIAL = "DELETE_TUTORIAL";
export const DELETE_ALL_TUTORIALS = "DELETE_ALL_TUTORIALS";
//products type
export const LIST_PRODUCTS= "LIST_PRODUCTS";
export const CREATE_PRODUCT="CREATE_PRODUCT";
export const UPDATE_PRODUCT="UPDATE_PRODUCT";
export const DELETE_PRODUCT="DELETE_PRODUCT";
//orders type
export const LIST_ORDERS  = "LIST_ORDERS";
export const CREATE_ORDER="CREATE_ORDER";
export const UPDATE_ORDER="UPDATE_ORDER";
export const DELETE_ORDER="DELETE_ORDER";
//categories type
export const LIST_CATEGORIES= "LIST_CATEGORIES";
export const CREATE_CATEGORY="CREATE_CATEGORY";
export const UPDATE_CATEGORY="UPDATE_CATEGORY";
export const DELETE_CATEGORY="DELETE_CATEGORY";
